---
swagger: "2.0"
info:
  description: "Provide"
  version: "1.0.0"
  title: "MOLD API"
host: "api.mo-ld.org"
basePath: "/v1"
schemes:
- "https"
produces:
- "application/rdf+xml"
- "application/json-ld"
- "text/ntriples"
- "text/tab-separated-values"
- "text/csv"
paths:
  /describe:
    get:
      tags:
      - "describe"
      summary: "Describe URI"
      description: "The Describe endpoint returns a graph that describe a resource\
        \ in RDF graph.\n"
      parameters:
      - name: "uri"
        in: "query"
        description: "URI to describe"
        required: true
        type: "string"
        format: "string"
      - name: "long"
        in: "query"
        description: "Either a short describe [0] (property attributes only) or a\
          \ full describe (with ingoing/outgoing links) [1]"
        required: false
        type: "integer"
        format: "int32"
      - name: "format"
        in: "query"
        description: "return format (rdf/xml, ntriples, nquads, turtle, json-ld)"
        required: false
        type: "string"
        format: "string"
      responses:
        200:
          description: "Success"
        default:
          description: "Unexpected error"
  /inlinks:
    get:
      tags:
      - "links"
      summary: "Get the incoming links"
      description: "The inlinks call will return a list of triples that target the\
        \ input URI.\n"
      parameters:
      - name: "uri"
        in: "query"
        description: "URI to describe"
        required: true
        type: "string"
        format: "string"
      - name: "format"
        in: "query"
        description: "return format (rdf/xml, ntriples, nquads, turtle, json-ld)"
        required: false
        type: "string"
        format: "string"
      responses:
        200:
          description: "Success"
        default:
          description: "Unexpected error"
  /outlinks:
    get:
      tags:
      - "links"
      summary: "Get the outgoing links"
      description: "The outlinks call will return a list of triples that target the\
        \ input URI.\n"
      parameters:
      - name: "uri"
        in: "query"
        description: "URI to describe"
        required: true
        type: "string"
        format: "string"
      - name: "format"
        in: "query"
        description: "return format (rdf/xml, ntriples, nquads, turtle, json-ld)"
        required: false
        type: "string"
        format: "string"
      responses:
        200:
          description: "Success"
        default:
          description: "Unexpected error"
  /search:
    get:
      tags:
      - "search"
      summary: "Search labels"
      description: "The Search endpoint returns a graph of URI resources, its namespace\
        \ and the\nlables that had a potential hit from the kword search.\n"
      parameters:
      - name: "q"
        in: "query"
        description: "Keyword search"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "A graph of resources retrieved from the kwords query."
        default:
          description: "Unexpected error"
  /sparql:
    get:
      tags:
      - "sparql"
      summary: "SPARQL GET"
      description: "SPARQL query either sent via a GET or POST\n"
      parameters:
      - name: "query"
        in: "query"
        description: "SPARQL"
        required: true
        type: "string"
        format: "string"
      - name: "format"
        in: "query"
        description: "return format (rdf/xml, ntriples, nquads, turtle, json-ld)"
        required: false
        type: "string"
        format: "string"
      responses:
        200:
          description: "Success"
        default:
          description: "Unexpected error"
    post:
      tags:
      - "sparql"
      summary: "SPARQL POST"
      description: "SPARQL query either sent via a GET or POST\n"
      parameters:
      - name: "query"
        in: "query"
        description: "SPARQL"
        required: true
        type: "string"
        format: "string"
      - name: "format"
        in: "query"
        description: "return format (rdf/xml, ntriples, nquads, turtle, json-ld)"
        required: false
        type: "string"
        format: "string"
      responses:
        200:
          description: "Success"
        default:
          description: "Unexpected error"
definitions: {}
